// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDongHoLG.Data;

#nullable disable

namespace WebDongHoLG.Migrations
{
    [DbContext(typeof(ShopDongHoDbContext))]
    [Migration("20260327111720_addmabienthetodanhgia")]
    partial class addmabienthetodanhgia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.BienTheSanPham", b =>
                {
                    b.Property<int>("MaBienThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maBienThe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBienThe"));

                    b.Property<string>("ChatLieuDay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chatLieuDay");

                    b.Property<int?>("DuongKinhMat")
                        .HasColumnType("int")
                        .HasColumnName("duongKinhMat");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("giaBan");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("giaNhap");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imageUrl");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("MaSku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("maSKU");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("maSp");

                    b.Property<string>("MauSac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mauSac");

                    b.HasKey("MaBienThe")
                        .HasName("PK__BienTheS__CFD6B0B9B4CD9442");

                    b.HasIndex("MaSp");

                    b.ToTable("BienTheSanPham", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("maDonHang");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int")
                        .HasColumnName("maBienThe");

                    b.Property<decimal?>("DonGiaTaiThoiDiem")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("donGiaTaiThoiDiem");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.HasKey("MaDonHang", "MaBienThe");

                    b.HasIndex("MaBienThe");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.Faq", b =>
                {
                    b.Property<int>("IdFaq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFAQ");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFaq"));

                    b.Property<string>("CauHoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cauHoi");

                    b.Property<string>("CauTraLoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cauTraLoi");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("IdFaq")
                        .HasName("PK__FAQ__39CD51D041A94D26");

                    b.ToTable("FAQ", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGioHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang__2C76D2032AD946F4");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.HinhAnhBienThe", b =>
                {
                    b.Property<int>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idHinhAnh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHinhAnh"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imageUrl");

                    b.Property<bool?>("LaAnhChinh")
                        .HasColumnType("bit")
                        .HasColumnName("laAnhChinh");

                    b.Property<int?>("MaBienThe")
                        .HasColumnType("int")
                        .HasColumnName("maBienThe");

                    b.Property<int?>("ThuTuHienThi")
                        .HasColumnType("int")
                        .HasColumnName("thuTuHienThi");

                    b.HasKey("IdHinhAnh")
                        .HasName("PK__HinhAnhB__4187C930E7E48F85");

                    b.HasIndex("MaBienThe");

                    b.ToTable("HinhAnhBienThe", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.Kho", b =>
                {
                    b.Property<int>("IdKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idKho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKho"));

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int")
                        .HasColumnName("maBienThe");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("soLuongTon");

                    b.HasKey("IdKho")
                        .HasName("PK__Kho__3FBE9E30C4176819");

                    b.HasIndex("MaBienThe");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.LichSuDonHang", b =>
                {
                    b.Property<int>("IdLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLichSu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichSu"));

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("maDonHang");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nguoiCapNhat");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianCapNhat");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThaiCu");

                    b.Property<string>("TrangThaiMoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThaiMoi");

                    b.HasKey("IdLichSu")
                        .HasName("PK__LichSuDo__C6FF3816F59E239E");

                    b.HasIndex("MaDonHang");

                    b.ToTable("LichSuDonHang", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.LichSuTuVanAi", b =>
                {
                    b.Property<int>("MaTuVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maTuVan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuVan"));

                    b.Property<string>("CauHoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cauHoi");

                    b.Property<string>("CauTraLoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cauTraLoi");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGian");

                    b.HasKey("MaTuVan")
                        .HasName("PK__LichSuTu__E93A68B59F52ECC2");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuTuVanAI", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anhDaiDien");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__446439EA8A038624");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.NhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaNhapLuuTru")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__NhapKho__3214EC0713937234");

                    b.HasIndex("MaBienThe");

                    b.ToTable("NhapKho", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maSp");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<string>("DoiTuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("doiTuong");

                    b.Property<int?>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("idDanhMuc");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenSanPham");

                    b.Property<int?>("ThuongHieuId")
                        .HasColumnType("int");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__7A227A5A7BDC6FB9");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("ThuongHieuId");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.ThanhToan", b =>
                {
                    b.Property<int>("IdThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idThanhToan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhToan"));

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("maDonHang");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phuongThuc");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianThanhToan");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("IdThanhToan")
                        .HasName("PK__ThanhToa__2DE12A667F86F32A");

                    b.HasIndex(new[] { "MaDonHang" }, "UQ__ThanhToa__871D38184511D759")
                        .IsUnique()
                        .HasFilter("[maDonHang] IS NOT NULL");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.ThongSoSanPham", b =>
                {
                    b.Property<int>("IdThongSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idThongSo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongSo"));

                    b.Property<string>("GiaTri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("giaTri");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("maSp");

                    b.Property<string>("TenThongSo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenThongSo");

                    b.HasKey("IdThongSo")
                        .HasName("PK__ThongSoS__0816FFC2CFE26183");

                    b.HasIndex("MaSp");

                    b.ToTable("ThongSoSanPham", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.ThuongHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Data.Voucher", b =>
                {
                    b.Property<int>("MaVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVoucher"));

                    b.Property<int?>("DaDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("GiaTriToiThieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<double>("PhanTramGiam")
                        .HasColumnType("float");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVoucher")
                        .HasName("PK__Voucher__0AAC5B11BDA1118B");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .HasColumnType("int")
                        .HasColumnName("maGioHang");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int")
                        .HasColumnName("maBienThe");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.HasKey("MaGioHang", "MaBienThe");

                    b.HasIndex("MaBienThe");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Models.DanhGium", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maDanhGia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int?>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("maSp");

                    b.Property<DateTime?>("NgayDanhGia")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayDanhGia");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("noiDung");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("soSao");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DanhGia__6B15DD9A3DF1A8C8");

                    b.HasIndex("MaBienThe");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSp");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebDongHoLG.Models.DanhMucSanPham", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDanhMuc");

                    b.HasKey("IdDanhMuc")
                        .HasName("PK__DanhMucS__927F1878D3D46117");

                    b.ToTable("DanhMucSanPham", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Models.DiaChiGiaoHang", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maDiaChi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaChi"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghiChu");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<string>("SdtNhanHang")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdtNhanHang");

                    b.HasKey("MaDiaChi")
                        .HasName("PK__DiaChiGi__0A7DF6203061843A");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DiaChiGiaoHang", (string)null);
                });

            modelBuilder.Entity("WebDongHoLG.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maDonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<int?>("MaDiaChi")
                        .HasColumnType("int")
                        .HasColumnName("maDiaChi");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<int?>("MaVoucher")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayDat")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("tongTien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__871D3819019D948B");

                    b.HasIndex("MaDiaChi");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaVoucher");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebDongHoLG.Data.BienTheSanPham", b =>
                {
                    b.HasOne("WebDongHoLG.Data.SanPham", "MaSpNavigation")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__BienTheSan__maSp__4BAC3F29");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("WebDongHoLG.Data.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaBienThe")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__maBie__5EBF139D");

                    b.HasOne("WebDongHoLG.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__maDon__5DCAEF64");

                    b.Navigation("MaBienTheNavigation");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.GioHang", b =>
                {
                    b.HasOne("WebDongHoLG.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__GioHang__maNguoi__5535A963");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.HinhAnhBienThe", b =>
                {
                    b.HasOne("WebDongHoLG.Data.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany("HinhAnhBienThes")
                        .HasForeignKey("MaBienThe")
                        .HasConstraintName("FK__HinhAnhBi__maBie__4E88ABD4");

                    b.Navigation("MaBienTheNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.Kho", b =>
                {
                    b.HasOne("WebDongHoLG.Data.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany("Khos")
                        .HasForeignKey("MaBienThe")
                        .IsRequired()
                        .HasConstraintName("FK__Kho__maBienThe__656C112C");

                    b.Navigation("MaBienTheNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.LichSuDonHang", b =>
                {
                    b.HasOne("WebDongHoLG.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("LichSuDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK__LichSuDon__maDon__72C60C4A");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.LichSuTuVanAi", b =>
                {
                    b.HasOne("WebDongHoLG.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("LichSuTuVanAis")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__LichSuTuV__maNgu__75A278F5");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.NguoiDung", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("WebDongHoLG.Data.NhapKho", b =>
                {
                    b.HasOne("WebDongHoLG.Data.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany("NhapKhos")
                        .HasForeignKey("MaBienThe")
                        .HasConstraintName("FK__NhapKho__MaBienT__68487DD7");

                    b.Navigation("MaBienTheNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.SanPham", b =>
                {
                    b.HasOne("WebDongHoLG.Models.DanhMucSanPham", "IdDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhMuc")
                        .HasConstraintName("FK__SanPham__idDanhM__44FF419A");

                    b.HasOne("WebDongHoLG.Data.ThuongHieu", "ThuongHieuNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("ThuongHieuId")
                        .HasConstraintName("FK_SanPham_ThuongHieu");

                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("ThuongHieuNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.ThanhToan", b =>
                {
                    b.HasOne("WebDongHoLG.Models.DonHang", "MaDonHangNavigation")
                        .WithOne("ThanhToan")
                        .HasForeignKey("WebDongHoLG.Data.ThanhToan", "MaDonHang")
                        .HasConstraintName("FK__ThanhToan__maDon__6C190EBB");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.ThongSoSanPham", b =>
                {
                    b.HasOne("WebDongHoLG.Data.SanPham", "MaSpNavigation")
                        .WithMany("ThongSoSanPhams")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__ThongSoSan__maSp__47DBAE45");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("WebDongHoLG.Data.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaBienThe")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGi__maBie__628FA481");

                    b.HasOne("WebDongHoLG.Data.GioHang", "MaGioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGi__maGio__619B8048");

                    b.Navigation("MaBienTheNavigation");

                    b.Navigation("MaGioHangNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Models.DanhGium", b =>
                {
                    b.HasOne("WebDongHoLG.Data.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany()
                        .HasForeignKey("MaBienThe")
                        .HasConstraintName("FK_DanhGia_BienThe");

                    b.HasOne("WebDongHoLG.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__DanhGia__maNguoi__6EF57B66");

                    b.HasOne("WebDongHoLG.Data.SanPham", "MaSpNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__DanhGia__maSp__6FE99F9F");

                    b.Navigation("MaBienTheNavigation");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Models.DiaChiGiaoHang", b =>
                {
                    b.HasOne("WebDongHoLG.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DiaChiGiaoHangs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__DiaChiGia__maNgu__5165187F");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Models.DonHang", b =>
                {
                    b.HasOne("WebDongHoLG.Models.DiaChiGiaoHang", "MaDiaChiNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaDiaChi")
                        .HasConstraintName("FK__DonHang__maDiaCh__59FA5E80");

                    b.HasOne("WebDongHoLG.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__DonHang__maNguoi__59063A47");

                    b.HasOne("WebDongHoLG.Data.Voucher", "MaVoucherNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaVoucher")
                        .HasConstraintName("FK__DonHang__MaVouch__5AEE82B9");

                    b.Navigation("MaDiaChiNavigation");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaVoucherNavigation");
                });

            modelBuilder.Entity("WebDongHoLG.Data.BienTheSanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("HinhAnhBienThes");

                    b.Navigation("Khos");

                    b.Navigation("NhapKhos");
                });

            modelBuilder.Entity("WebDongHoLG.Data.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("WebDongHoLG.Data.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DiaChiGiaoHangs");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("LichSuTuVanAis");
                });

            modelBuilder.Entity("WebDongHoLG.Data.SanPham", b =>
                {
                    b.Navigation("BienTheSanPhams");

                    b.Navigation("DanhGia");

                    b.Navigation("ThongSoSanPhams");
                });

            modelBuilder.Entity("WebDongHoLG.Data.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebDongHoLG.Data.Voucher", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebDongHoLG.Models.DanhMucSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebDongHoLG.Models.DiaChiGiaoHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebDongHoLG.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LichSuDonHangs");

                    b.Navigation("ThanhToan");
                });
#pragma warning restore 612, 618
        }
    }
}
